[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "confostate"
version = "0.1.0"
description = "Classify membrane protein structures into conformational states"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "ConfoState Contributors"}
]

dependencies = [
    "numpy>=2.0",
    "requests"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=22.0",
    "flake8>=4.0",
]

[tool.setuptools]
packages = ["confostate"]

[tool.setuptools.package-data]
confostate = ["data/**/*"]
